// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: core/credit/credit.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Credit struct {
	Owner      string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Credited   uint64   `protobuf:"varint,2,opt,name=credited,proto3" json:"credited,omitempty"`
	Rewarding  uint64   `protobuf:"varint,3,opt,name=rewarding,proto3" json:"rewarding,omitempty"`
	Collateral []uint64 `protobuf:"varint,4,rep,packed,name=collateral,proto3" json:"collateral,omitempty"`
	Bond       uint64   `protobuf:"varint,5,opt,name=bond,proto3" json:"bond,omitempty"`
}

func (m *Credit) Reset()         { *m = Credit{} }
func (m *Credit) String() string { return proto.CompactTextString(m) }
func (*Credit) ProtoMessage()    {}
func (*Credit) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d99e56985f5e7bc, []int{0}
}
func (m *Credit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Credit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Credit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Credit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credit.Merge(m, src)
}
func (m *Credit) XXX_Size() int {
	return m.Size()
}
func (m *Credit) XXX_DiscardUnknown() {
	xxx_messageInfo_Credit.DiscardUnknown(m)
}

var xxx_messageInfo_Credit proto.InternalMessageInfo

func (m *Credit) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Credit) GetCredited() uint64 {
	if m != nil {
		return m.Credited
	}
	return 0
}

func (m *Credit) GetRewarding() uint64 {
	if m != nil {
		return m.Rewarding
	}
	return 0
}

func (m *Credit) GetCollateral() []uint64 {
	if m != nil {
		return m.Collateral
	}
	return nil
}

func (m *Credit) GetBond() uint64 {
	if m != nil {
		return m.Bond
	}
	return 0
}

func init() {
	proto.RegisterType((*Credit)(nil), "core.credit.Credit")
}

func init() { proto.RegisterFile("core/credit/credit.proto", fileDescriptor_1d99e56985f5e7bc) }

var fileDescriptor_1d99e56985f5e7bc = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0xce, 0x2f, 0x4a,
	0xd5, 0x4f, 0x2e, 0x4a, 0x4d, 0xc9, 0x2c, 0x81, 0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xdc, 0x20, 0x19, 0x3d, 0x88, 0x90, 0x52, 0x0f, 0x23, 0x17, 0x9b, 0x33, 0x98, 0x29, 0x24, 0xc2,
	0xc5, 0x9a, 0x5f, 0x9e, 0x97, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08,
	0x49, 0x71, 0x71, 0x40, 0x94, 0xa6, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x04, 0xc1, 0xf9,
	0x42, 0x32, 0x5c, 0x9c, 0x45, 0xa9, 0xe5, 0x89, 0x45, 0x29, 0x99, 0x79, 0xe9, 0x12, 0xcc, 0x60,
	0x49, 0x84, 0x80, 0x90, 0x1c, 0x17, 0x57, 0x72, 0x7e, 0x4e, 0x4e, 0x62, 0x49, 0x6a, 0x51, 0x62,
	0x8e, 0x04, 0x8b, 0x02, 0xb3, 0x06, 0x4b, 0x10, 0x92, 0x88, 0x90, 0x10, 0x17, 0x4b, 0x52, 0x7e,
	0x5e, 0x8a, 0x04, 0x2b, 0x58, 0x23, 0x98, 0xed, 0xa4, 0x7b, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47,
	0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d,
	0xc7, 0x72, 0x0c, 0x51, 0xc2, 0x60, 0xff, 0x54, 0xc0, 0x7c, 0x54, 0x52, 0x59, 0x90, 0x5a, 0x9c,
	0xc4, 0x06, 0xf6, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x6c, 0x44, 0xa1, 0xed, 0x00,
	0x00, 0x00,
}

func (m *Credit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Credit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Credit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Bond != 0 {
		i = encodeVarintCredit(dAtA, i, uint64(m.Bond))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Collateral) > 0 {
		dAtA2 := make([]byte, len(m.Collateral)*10)
		var j1 int
		for _, num := range m.Collateral {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintCredit(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if m.Rewarding != 0 {
		i = encodeVarintCredit(dAtA, i, uint64(m.Rewarding))
		i--
		dAtA[i] = 0x18
	}
	if m.Credited != 0 {
		i = encodeVarintCredit(dAtA, i, uint64(m.Credited))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintCredit(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCredit(dAtA []byte, offset int, v uint64) int {
	offset -= sovCredit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Credit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovCredit(uint64(l))
	}
	if m.Credited != 0 {
		n += 1 + sovCredit(uint64(m.Credited))
	}
	if m.Rewarding != 0 {
		n += 1 + sovCredit(uint64(m.Rewarding))
	}
	if len(m.Collateral) > 0 {
		l = 0
		for _, e := range m.Collateral {
			l += sovCredit(uint64(e))
		}
		n += 1 + sovCredit(uint64(l)) + l
	}
	if m.Bond != 0 {
		n += 1 + sovCredit(uint64(m.Bond))
	}
	return n
}

func sovCredit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCredit(x uint64) (n int) {
	return sovCredit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Credit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCredit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Credit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Credit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credited", wireType)
			}
			m.Credited = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Credited |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewarding", wireType)
			}
			m.Rewarding = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rewarding |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCredit
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Collateral = append(m.Collateral, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCredit
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthCredit
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthCredit
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Collateral) == 0 {
					m.Collateral = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCredit
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Collateral = append(m.Collateral, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
			}
			m.Bond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Bond |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCredit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCredit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCredit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCredit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCredit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCredit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCredit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCredit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCredit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCredit = fmt.Errorf("proto: unexpected end of group")
)
