// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: igmf/credit/credit.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Credit struct {
	Index             string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Owner             string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Denom             string `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	DenomAmount       uint64 `protobuf:"varint,4,opt,name=denomAmount,proto3" json:"denomAmount,omitempty"`
	Credited          uint64 `protobuf:"varint,5,opt,name=credited,proto3" json:"credited,omitempty"`
	Rewarding         uint64 `protobuf:"varint,6,opt,name=rewarding,proto3" json:"rewarding,omitempty"`
	LastRewardedBlock uint64 `protobuf:"varint,7,opt,name=lastRewardedBlock,proto3" json:"lastRewardedBlock,omitempty"`
	Bond              uint64 `protobuf:"varint,8,opt,name=bond,proto3" json:"bond,omitempty"`
}

func (m *Credit) Reset()         { *m = Credit{} }
func (m *Credit) String() string { return proto.CompactTextString(m) }
func (*Credit) ProtoMessage()    {}
func (*Credit) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb029bc63fe65667, []int{0}
}
func (m *Credit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Credit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Credit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Credit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credit.Merge(m, src)
}
func (m *Credit) XXX_Size() int {
	return m.Size()
}
func (m *Credit) XXX_DiscardUnknown() {
	xxx_messageInfo_Credit.DiscardUnknown(m)
}

var xxx_messageInfo_Credit proto.InternalMessageInfo

func (m *Credit) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Credit) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Credit) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Credit) GetDenomAmount() uint64 {
	if m != nil {
		return m.DenomAmount
	}
	return 0
}

func (m *Credit) GetCredited() uint64 {
	if m != nil {
		return m.Credited
	}
	return 0
}

func (m *Credit) GetRewarding() uint64 {
	if m != nil {
		return m.Rewarding
	}
	return 0
}

func (m *Credit) GetLastRewardedBlock() uint64 {
	if m != nil {
		return m.LastRewardedBlock
	}
	return 0
}

func (m *Credit) GetBond() uint64 {
	if m != nil {
		return m.Bond
	}
	return 0
}

func init() {
	proto.RegisterType((*Credit)(nil), "igmf.credit.Credit")
}

func init() { proto.RegisterFile("igmf/credit/credit.proto", fileDescriptor_eb029bc63fe65667) }

var fileDescriptor_eb029bc63fe65667 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc8, 0x4c, 0xcf, 0x4d,
	0xd3, 0x4f, 0x2e, 0x4a, 0x4d, 0xc9, 0x2c, 0x81, 0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xdc, 0x20, 0x19, 0x3d, 0x88, 0x90, 0xd2, 0x0b, 0x46, 0x2e, 0x36, 0x67, 0x30, 0x53, 0x48, 0x84,
	0x8b, 0x35, 0x33, 0x2f, 0x25, 0xb5, 0x42, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x01,
	0x89, 0xe6, 0x97, 0xe7, 0xa5, 0x16, 0x49, 0x30, 0x41, 0x44, 0xc1, 0x1c, 0x90, 0x68, 0x4a, 0x6a,
	0x5e, 0x7e, 0xae, 0x04, 0x33, 0x44, 0x14, 0xcc, 0x11, 0x52, 0xe0, 0xe2, 0x06, 0x33, 0x1c, 0x73,
	0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x58, 0x14, 0x18, 0x35, 0x58, 0x82, 0x90, 0x85, 0x84, 0xa4, 0xb8,
	0x38, 0x20, 0x16, 0xa7, 0xa6, 0x48, 0xb0, 0x82, 0xa5, 0xe1, 0x7c, 0x21, 0x19, 0x2e, 0xce, 0xa2,
	0xd4, 0xf2, 0xc4, 0xa2, 0x94, 0xcc, 0xbc, 0x74, 0x09, 0x36, 0xb0, 0x24, 0x42, 0x40, 0x48, 0x87,
	0x4b, 0x30, 0x27, 0xb1, 0xb8, 0x24, 0x08, 0x2c, 0x90, 0x9a, 0xe2, 0x94, 0x93, 0x9f, 0x9c, 0x2d,
	0xc1, 0x0e, 0x56, 0x85, 0x29, 0x21, 0x24, 0xc4, 0xc5, 0x92, 0x94, 0x9f, 0x97, 0x22, 0xc1, 0x01,
	0x56, 0x00, 0x66, 0x3b, 0xe9, 0x9e, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47,
	0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94,
	0x30, 0x38, 0xac, 0x2a, 0x60, 0xa1, 0x55, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x0e, 0x2d,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0x06, 0x88, 0x95, 0x49, 0x01, 0x00, 0x00,
}

func (m *Credit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Credit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Credit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Bond != 0 {
		i = encodeVarintCredit(dAtA, i, uint64(m.Bond))
		i--
		dAtA[i] = 0x40
	}
	if m.LastRewardedBlock != 0 {
		i = encodeVarintCredit(dAtA, i, uint64(m.LastRewardedBlock))
		i--
		dAtA[i] = 0x38
	}
	if m.Rewarding != 0 {
		i = encodeVarintCredit(dAtA, i, uint64(m.Rewarding))
		i--
		dAtA[i] = 0x30
	}
	if m.Credited != 0 {
		i = encodeVarintCredit(dAtA, i, uint64(m.Credited))
		i--
		dAtA[i] = 0x28
	}
	if m.DenomAmount != 0 {
		i = encodeVarintCredit(dAtA, i, uint64(m.DenomAmount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintCredit(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintCredit(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintCredit(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCredit(dAtA []byte, offset int, v uint64) int {
	offset -= sovCredit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Credit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovCredit(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovCredit(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovCredit(uint64(l))
	}
	if m.DenomAmount != 0 {
		n += 1 + sovCredit(uint64(m.DenomAmount))
	}
	if m.Credited != 0 {
		n += 1 + sovCredit(uint64(m.Credited))
	}
	if m.Rewarding != 0 {
		n += 1 + sovCredit(uint64(m.Rewarding))
	}
	if m.LastRewardedBlock != 0 {
		n += 1 + sovCredit(uint64(m.LastRewardedBlock))
	}
	if m.Bond != 0 {
		n += 1 + sovCredit(uint64(m.Bond))
	}
	return n
}

func sovCredit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCredit(x uint64) (n int) {
	return sovCredit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Credit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCredit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Credit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Credit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomAmount", wireType)
			}
			m.DenomAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DenomAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credited", wireType)
			}
			m.Credited = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Credited |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewarding", wireType)
			}
			m.Rewarding = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rewarding |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastRewardedBlock", wireType)
			}
			m.LastRewardedBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastRewardedBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
			}
			m.Bond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Bond |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCredit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCredit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCredit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCredit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCredit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCredit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCredit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCredit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCredit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCredit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCredit = fmt.Errorf("proto: unexpected end of group")
)
